/* AUTO-GENERATED by toolkit/gen_shared_registry.js — 顯示 metadata，勿手改 */
window.WORKSHEET_REGISTRY = [
  {
    "id": "n2-change",
    "code": "N-2-7",
    "grade": "2",
    "name": "購物找零＿兩步驟乘減（兩位數）",
    "ops": [
      "mul",
      "sub",
      "mix"
    ],
    "keywords": [
      "找零",
      "付款",
      "兩步驟乘減"
    ],
    "desc": "價目表 4 件商品，3 道找零題：買1件A＋1件B找零、買3件A找零、買5件A找零（乘法＋減法兩步驟）。",
    "sortKey": [
      3,
      2,
      2
    ],
    "home": {
      "icon": "🛒",
      "sub": "乘法 × 減法",
      "desc": "學生到店裡購物，計算找零金額，練習乘法應用加付款找零的兩步驟計算。",
      "features": [
        "買東西計算找零",
        "乘法＋減法兩步驟",
        "3 道題全自動配置"
      ]
    },
    "diffInfo": null,
    "sample": {
      "pdf": "assets/n2change_sample.pdf",
      "name": "購物找零_兩步驟乘減_兩位數_範本.pdf"
    },
    "layout": {
      "panel": null,
      "themeSet": "cheap",
      "showTheme": true,
      "prices": false,
      "interactive": true
    }
  },
  {
    "id": "maxbuy",
    "code": "N-2-8",
    "grade": "2",
    "name": "最多能買幾個＿預算判斷（兩位數）",
    "ops": [
      "mul",
      "div"
    ],
    "keywords": [
      "最多能買",
      "買幾個",
      "預算",
      "預算判斷",
      "口袋有幾元"
    ],
    "desc": "口袋有 N 元，單件商品定價後，學生逐一計算買 2 個、3 個…的花費，找出不超出預算的最大數量（答案落在 3～5 個）。",
    "sortKey": [
      3,
      2,
      1
    ],
    "home": {
      "icon": "💰",
      "sub": "預算 × 判斷",
      "desc": "口袋有 N 元，最多能買幾件？學生逐步計算每個數量的總金額，找出不超預算的最大數量。",
      "features": [
        "以乘法試算不同數量",
        "比較總金額與預算",
        "找出最大可購買數量"
      ]
    },
    "diffInfo": null,
    "sample": {
      "pdf": "assets/maxbuy_sample.pdf",
      "name": "最多能買幾個_預算判斷_兩位數_範本.pdf"
    },
    "layout": {
      "panel": null,
      "themeSet": "cheap",
      "showTheme": true,
      "prices": false,
      "interactive": true
    }
  },
  {
    "id": "sanbushu",
    "code": "N-2-7",
    "grade": "2",
    "name": "購物找零＿三步驟乘加減（兩位數）",
    "ops": [
      "mul",
      "add",
      "sub",
      "mix"
    ],
    "keywords": [
      "三步驟",
      "加減混合",
      "買兩種",
      "合計找零"
    ],
    "desc": "1頁：5個Menu商品＋2道題（各買兩種商品求合計後找零）。題目全自動產生，只需選主題。",
    "sortKey": [
      3,
      2,
      3
    ],
    "home": {
      "icon": "📋",
      "sub": "加減混合",
      "desc": "買兩種商品求合計，再計算付款後的找零，三步驟串聯練習加減混合。",
      "features": [
        "買兩種商品求合計",
        "計算付款後找零",
        "題目全自動產生"
      ]
    },
    "diffInfo": {
      "grade": "二年級",
      "level": "中等",
      "levelColor": "#f59e0b",
      "code": "N-2-7",
      "desc": "三步驟乘加減混合，需有乘法基礎；出題含 Menu 閱讀與多步計算。"
    },
    "sample": {
      "pdf": "assets/sanbushu_sample.pdf",
      "name": "購物找零_三步驟乘加減_兩位數_範本.pdf"
    },
    "layout": {
      "panel": "sanbushuPanel",
      "themeSet": "cheap",
      "showTheme": true,
      "prices": true,
      "interactive": false
    }
  },
  {
    "id": "fenfen",
    "code": "N-2-3",
    "grade": "2",
    "name": "分分看＿一步驟除法（兩位數）",
    "ops": [
      "div"
    ],
    "keywords": [
      "fenfen",
      "分分看",
      "圈一圈",
      "等分",
      "除法",
      "花",
      "氣球",
      "糖果"
    ],
    "desc": "同一設定頁含 A、B 兩版。A版：從圖庫隨機挑選 3 種物件，圖示預先印好，學生數數填答；B版：可選 11 種主題，系統自動產生圖示，除數每次隨機。",
    "sortKey": [
      4,
      2,
      1
    ],
    "home": {
      "icon": "🌼",
      "sub": "除法概念（5 種版型）",
      "desc": "5 種版型統一在同一設定頁：圖示預印填答、有餘數、分堆畫圈、分盤畫圈、分盤格線，涵蓋等組與等分除法。",
      "features": [
        "無餘數：圖示預印，可選 11 種主題",
        "有餘數：固定圖片，計算商與餘數",
        "B版 3 種：學生自行畫圈，純換數字"
      ]
    },
    "diffInfo": {
      "grade": "二年級",
      "level": "基礎",
      "levelColor": "#22c55e",
      "code": "N-2-3",
      "desc": "A版圖示預先繪好，學生數一數即可填答；B版可選主題，圖示隨機產生，是認識等分除法的第一步。"
    },
    "sample": [
      { "pdf": "assets/fenfennew_sample.pdf", "name": "分分看_無餘數_範例.pdf", "label": "無餘數", "key": "fenfennew" },
      { "pdf": "assets/fenfen_rem_sample.pdf", "name": "分分看_有餘數_範例.pdf", "label": "有餘數", "key": "fenfen-rem" },
      { "pdf": "assets/fenfen_heap_sample.pdf", "name": "分分看_分堆畫圈_範例.pdf", "label": "分堆畫圈", "key": "fenfen-heap" },
      { "pdf": "assets/fenfen_pan_sample.pdf", "name": "分分看_分盤畫圈_範例.pdf", "label": "分盤畫圈", "key": "fenfen-pan" },
      { "pdf": "assets/fenfen_pangrid_sample.pdf", "name": "分分看_分盤格線_範例.pdf", "label": "分盤格線", "key": "fenfen-pangrid" }
    ],
    "layout": {
      "panel": "fenfenPanel",
      "themeSet": "cheap",
      "showTheme": false,
      "prices": false,
      "interactive": false
    },
    "variants": [
      {
        "key": "fenfennew",
        "label": "無餘數"
      },
      {
        "key": "fenfen-rem",
        "label": "有餘數"
      },
      {
        "key": "fenfen-heap",
        "label": "分堆畫圈"
      },
      {
        "key": "fenfen-pan",
        "label": "分盤畫圈"
      },
      {
        "key": "fenfen-pangrid",
        "label": "分盤格線"
      }
    ]
  },
  {
    "id": "pingfen",
    "code": "N-2-5",
    "grade": "2",
    "name": "平分問題＿一步驟除乘（兩位數）",
    "ops": [
      "mul",
      "div"
    ],
    "keywords": [
      "平分",
      "平均數",
      "等分",
      "乘法連結"
    ],
    "desc": "把N個物件平分給X個人，一個人有幾個？從加法算式（□+□+□）延伸到乘法（□×3），建立等分除法與乘法的連結關係。固定5題，適合乘法初學者。",
    "sortKey": [
      4,
      2,
      1
    ],
    "home": {
      "icon": "⚖️",
      "sub": "除法→乘法",
      "desc": "把物品平均分配給每個人，從加法延伸到乘法算式，連結平分與乘法的關係。",
      "features": [
        "平分→加法→乘法三步驟",
        "找出平均數概念",
        "固定5題靜態學習單"
      ]
    },
    "diffInfo": {
      "grade": "二年級",
      "level": "基礎",
      "levelColor": "#22c55e",
      "code": "N-2-5",
      "desc": "把 N 個物件平分給 X 人，連結加法（□＋□＋□）與乘法（□×X）。"
    },
    "sample": {
      "pdf": "assets/pingfen_sample.pdf",
      "name": "平分問題_一步驟除乘_兩位數_範本.pdf"
    },
    "layout": {
      "panel": "pingfenPanel",
      "themeSet": "cheap",
      "showTheme": false,
      "prices": false,
      "interactive": false
    }
  },
  {
    "id": "liangbushu",
    "code": "N-2-4",
    "grade": "2",
    "name": "購物找零＿兩步驟加減（四位數）",
    "ops": [
      "add",
      "sub",
      "mix"
    ],
    "keywords": [
      "兩步驟",
      "四位數",
      "加減混合",
      "找零合計"
    ],
    "desc": "價目表列出 5 件千元商品，選 2 件計算合計（加法），再從付款金額扣除找零（減法），建立四位數加減兩步驟的計算流程。",
    "sortKey": [
      2,
      4,
      2
    ],
    "home": {
      "icon": "🏷️",
      "sub": "四位數加減",
      "desc": "千元商品價目表，選兩件商品計算合計，再從付款金額找零，建立四位數兩步驟計算流程。",
      "features": [
        "四位數加法→合計",
        "四位數減法→找零",
        "題目全自動產生"
      ]
    },
    "diffInfo": {
      "grade": "二年級",
      "level": "進階",
      "levelColor": "#f97316",
      "code": "N-2-4",
      "desc": "四位數兩步驟加減（先加求合計，再減求找零），適合熟悉進退位的學生。"
    },
    "sample": {
      "pdf": "assets/liangbushu_sample.pdf",
      "name": "購物找零_兩步驟加減_四位數_範本.pdf"
    },
    "layout": {
      "panel": "liangbushuPanel",
      "themeSet": "expensive",
      "themes": [
        "玩具車",
        "懷舊玩具",
        "體育用品店"
      ],
      "showTheme": true,
      "prices": true,
      "interactive": false
    }
  },
  {
    "id": "chenghe",
    "code": "N-2-7",
    "grade": "2",
    "name": "倍數購物＿兩步驟乘減（兩位數）",
    "ops": [
      "mul",
      "sub",
      "mix"
    ],
    "keywords": [
      "先乘後減",
      "九九乘法",
      "找零",
      "兩步驟"
    ],
    "desc": "價目表 5 件商品，買 N 件後計算合計（乘法），再從付款金額找零（減法），每題左右雙欄，3 道題自動隨機。",
    "sortKey": [
      3,
      2,
      2
    ],
    "home": {
      "icon": "✖️",
      "sub": "乘法→找零",
      "desc": "買同款商品 N 件，先用乘法算合計，再從付款金額找零，九九乘法的生活應用兩步驟練習。",
      "features": [
        "乘法求合計",
        "減法求找零",
        "3 道題全自動隨機"
      ]
    },
    "diffInfo": {
      "grade": "二年級",
      "level": "進階",
      "levelColor": "#f97316",
      "code": "N-2-7",
      "desc": "九九乘法兩步驟：先乘法求合計，再付款找零，每頁 3 道題，適合乘法已熟練的學生。"
    },
    "sample": {
      "pdf": "assets/chenghe_sample.pdf",
      "name": "倍數購物_兩步驟乘減_兩位數_範本.pdf"
    },
    "layout": {
      "panel": "chenghePanel",
      "themeSet": "cheap",
      "showTheme": true,
      "prices": true,
      "interactive": false
    }
  },
  {
    "id": "haochashao",
    "code": "N-2-4",
    "grade": "2",
    "name": "還差多少＿一步驟減法（兩位數）",
    "ops": [
      "sub"
    ],
    "keywords": [
      "還差多少",
      "不夠",
      "存款",
      "減法"
    ],
    "desc": "甜點店 4 件商品，學生存了一些錢還不夠買，計算還差幾元。共 6 道題，數字每次隨機產生。",
    "sortKey": [
      2,
      2,
      1
    ],
    "home": {
      "icon": "🏷️",
      "sub": "一步驟減法",
      "desc": "甜點店商品標價，學生存了一些錢卻不夠，計算還差多少元才能買到，建立減法的生活情境。",
      "features": [
        "標價－存款＝還差多少",
        "甜點店 4 件商品",
        "6 道題全自動隨機"
      ]
    },
    "diffInfo": {
      "grade": "二年級",
      "level": "基礎",
      "levelColor": "#22c55e",
      "code": "N-2-4",
      "desc": "甜點店 4 件商品，學生手邊有一些錢但不夠，計算還差幾元。一步驟減法，適合剛學減法的學生。"
    },
    "sample": {
      "pdf": "assets/haochashao_sample.pdf",
      "name": "還差多少_一步驟減法_兩位數_範本.pdf"
    },
    "layout": {
      "panel": "haochashaoPanel",
      "themeSet": "cheap",
      "themes": [
        "飲料店",
        "文具店",
        "甜點店"
      ],
      "showTheme": true,
      "prices": true,
      "interactive": false
    }
  },
  {
    "id": "huachu4add",
    "code": "N-3-1",
    "grade": "3",
    "name": "不進位的加法（四位數）＿畫錢幣輔助",
    "ops": [
      "add"
    ],
    "keywords": [
      "畫出錢幣",
      "四位數",
      "不進位",
      "加法",
      "錢幣"
    ],
    "desc": "5 道四位數不進位加法題（畫出錢幣並計算），搭配寫一寫練習千位遞增數列。數字每次隨機產生，不進位保證每位數和 ≤ 9。",
    "sortKey": [
      1,
      4,
      1
    ],
    "home": {
      "icon": "🪙",
      "sub": "四位數不進位加法",
      "desc": "畫出錢幣表示四位數，5 道不進位加法題，搭配寫一寫練習千位遞增，建立四位數加法的數感。",
      "features": [
        "四位數不進位加法",
        "畫出錢幣輔助理解",
        "寫一寫千位遞增練習"
      ]
    },
    "diffInfo": {
      "grade": "三年級",
      "level": "基礎",
      "levelColor": "#22c55e",
      "code": "N-3-1",
      "desc": "四位數加法（不進位），以畫錢幣輔助學生理解位值，適合四位數加法的入門練習。"
    },
    "sample": {
      "pdf": "assets/huachu4add_sample.pdf",
      "name": "不進位的加法_四位數_畫錢幣輔助_範本.pdf"
    },
    "layout": {
      "panel": "huachu4addPanel",
      "themeSet": "expensive",
      "showTheme": false,
      "prices": false,
      "interactive": false
    }
  },
  {
    "id": "huachu4sub",
    "code": "N-3-1",
    "grade": "3",
    "name": "不退位的減法（四位數）＿畫錢幣輔助",
    "ops": [
      "sub"
    ],
    "keywords": [
      "畫出錢幣",
      "四位數",
      "不退位",
      "減法",
      "錢幣"
    ],
    "desc": "5 道四位數不退位減法題（畫出錢幣並計算），搭配寫一寫練習千位遞減數列。數字每次隨機產生，不退位保證各位數 A ≥ B。",
    "sortKey": [
      2,
      4,
      1
    ],
    "home": {
      "icon": "🪙",
      "sub": "四位數不退位減法",
      "desc": "畫出錢幣表示四位數，5 道不退位減法題，搭配寫一寫練習千位遞減，建立四位數減法的數感。",
      "features": [
        "四位數不退位減法",
        "畫出錢幣輔助理解",
        "寫一寫千位遞減練習"
      ]
    },
    "diffInfo": {
      "grade": "三年級",
      "level": "基礎",
      "levelColor": "#22c55e",
      "code": "N-3-1",
      "desc": "四位數減法（不退位），以畫錢幣輔助學生理解位值，適合四位數減法的入門練習。"
    },
    "sample": {
      "pdf": "assets/huachu4sub_sample.pdf",
      "name": "不退位的減法_四位數_畫錢幣輔助_範本.pdf"
    },
    "layout": {
      "panel": "huachu4subPanel",
      "themeSet": "expensive",
      "showTheme": false,
      "prices": false,
      "interactive": false
    }
  },
  {
    "id": "tuiwei4sub",
    "code": "N-3-1",
    "grade": "3",
    "name": "退位減法（四位數）＿畫錢幣輔助",
    "ops": [
      "sub"
    ],
    "keywords": [
      "畫出錢幣",
      "四位數",
      "退位",
      "減法",
      "借位",
      "錢幣"
    ],
    "desc": "6 道四位數退位減法題，依選定借位模式隨機產生：百位借位、十位借位、或雙重借位。搭配錢幣輔助格供學生畫錢幣後計算。",
    "sortKey": [
      2,
      4,
      1
    ],
    "home": {
      "icon": "🪙",
      "sub": "四位數退位減法",
      "desc": "畫出錢幣表示四位數，6 道退位減法題，可選百位借位、十位借位或雙重借位，建立四位數退位的借位概念。",
      "features": [
        "四位數退位減法",
        "三種借位模式可選",
        "畫出錢幣輔助理解"
      ]
    },
    "diffInfo": {
      "grade": "三年級",
      "level": "進階",
      "levelColor": "#f59e0b",
      "code": "N-3-1",
      "desc": "四位數減法（含退位），以畫錢幣輔助學生理解借位過程，提供百位借位、十位借位、雙重借位三種難度。"
    },
    "sample": [
      {
        "pdf": "assets/tuiwei4sub_bai_sample.pdf",
        "name": "退位減法_四位數_百位借位_範本.pdf",
        "label": "百位借位",
        "key": "tuiwei4sub-bai"
      },
      {
        "pdf": "assets/tuiwei4sub_shi_sample.pdf",
        "name": "退位減法_四位數_十位借位_範本.pdf",
        "label": "十位借位",
        "key": "tuiwei4sub-shi"
      },
      {
        "pdf": "assets/tuiwei4sub_double_sample.pdf",
        "name": "退位減法_四位數_雙重借位_範本.pdf",
        "label": "雙重借位",
        "key": "tuiwei4sub-double"
      }
    ],
    "layout": {
      "panel": "tuiwei4subPanel",
      "themeSet": "expensive",
      "showTheme": true,
      "prices": true,
      "interactive": false
    },
    "variants": [
      { "key": "tuiwei4sub-bai",    "label": "百位借位" },
      { "key": "tuiwei4sub-shi",    "label": "十位借位" },
      { "key": "tuiwei4sub-double", "label": "雙重借位" }
    ]
  },
  {
    "id": "tuiwei3sub",
    "code": "N-3-2",
    "name": "退位減法（三位數）＿畫錢幣／畫記輔助",
    "grade": 3,
    "ops": [
      "sub"
    ],
    "keywords": [],
    "desc": "三位數退位減法計算練習，提供單退位錢幣、雙退位錢幣、雙退位畫記三種版型",
    "sortKey": [
      2,
      3,
      1
    ],
    "home": {
      "icon": "🪙",
      "label": "三位數退位減法",
      "sub": "錢幣 / 畫記輔助"
    },
    "diffInfo": null,
    "sample": [
      { "pdf": "assets/tuiwei3sub_coin_sample.pdf", "name": "退位減法_三位數_單退位錢幣_範例.pdf", "label": "單退位錢幣", "key": "tuiwei3sub-coin" },
      { "pdf": "assets/tuiwei3sub_dcoin_sample.pdf", "name": "退位減法_三位數_雙退位錢幣_範例.pdf", "label": "雙退位錢幣", "key": "tuiwei3sub-dcoin" },
      { "pdf": "assets/tuiwei3sub_tally_sample.pdf", "name": "退位減法_三位數_雙退位畫記_範例.pdf", "label": "雙退位畫記", "key": "tuiwei3sub-tally" },
      { "pdf": "assets/tuiwei3sub-yw_sample.pdf", "name": "退位減法_三位數_應用題購物篇_範例.pdf", "label": "應用題（購物篇）", "key": "tuiwei3sub-yw" }
    ],
    "layout": {
      "panel": "tuiwei3subPanel",
      "themeSet": null,
      "showTheme": false,
      "prices": false,
      "interactive": false
    },
    "variants": [
      {
        "key": "tuiwei3sub-coin",
        "label": "單退位錢幣"
      },
      {
        "key": "tuiwei3sub-dcoin",
        "label": "雙退位錢幣"
      },
      {
        "key": "tuiwei3sub-tally",
        "label": "雙退位畫記"
      },
      {
        "key": "tuiwei3sub-yw",
        "label": "應用題（購物篇）"
      }
    ]
  },
  {
    "id": "sub1",
    "code": "N-1-1",
    "name": "加減計算練習＿減法（十以內）",
    "grade": 1,
    "ops": [
      "sub"
    ],
    "keywords": [
      "一位數",
      "減法",
      "十以內",
      "算術練習"
    ],
    "desc": "十以內各種減法，共 5 種版型：被減數 1–5／6–9／10、圖輔助版、退位減法，可依學生程度選擇。",
    "sortKey": [
      2,
      1,
      1
    ],
    "home": {
      "icon": "➖",
      "label": "十以內減法",
      "sub": "5 種版型選擇"
    },
    "diffInfo": null,
    "sample": [
      { "pdf": "assets/sub15_sample.pdf", "name": "十以內減法_被減數1-5_範例.pdf", "label": "被減數 1–5", "key": "sub15" },
      { "pdf": "assets/sub69_sample.pdf", "name": "十以內減法_被減數6-9_範例.pdf", "label": "被減數 6–9", "key": "sub69" },
      { "pdf": "assets/sub10_sample.pdf", "name": "十以內減法_被減數10_範例.pdf", "label": "被減數 10", "key": "sub10" },
      { "pdf": "assets/subfig_sample.pdf", "name": "十以內減法_圖輔助_範例.pdf", "label": "圖輔助", "key": "subfig" },
      { "pdf": "assets/subborrow_sample.pdf", "name": "十以內退位減法_範例.pdf", "label": "退位減法", "key": "subborrow" }
    ],
    "layout": {
      "panel": "sub1Panel",
      "themeSet": "cheap",
      "showTheme": false,
      "prices": false,
      "interactive": false
    },
    "variants": [
      {
        "key": "sub15",
        "label": "被減數 1–5"
      },
      {
        "key": "sub69",
        "label": "被減數 6–9"
      },
      {
        "key": "sub10",
        "label": "被減數 10"
      },
      {
        "key": "subfig",
        "label": "圖輔助"
      },
      {
        "key": "subborrow",
        "label": "退位減法"
      }
    ]
  },
  {
    "id": "tuiwei3sub-yw",
    "code": "N-3-2",
    "name": "退位減法（三位數）＿應用題＿購物篇",
    "grade": 3,
    "ops": [
      "sub"
    ],
    "keywords": [],
    "desc": "三位數退位減法情境題，購物情境，每題附商品圖片，個位均為 0，自動選三位數價位主題",
    "sortKey": [
      2,
      3,
      2
    ],
    "home": {
      "icon": "🛍️",
      "label": "三位數退位應用題",
      "sub": "購物篇情境"
    },
    "diffInfo": {
      "grade": "三年級",
      "level": "基礎",
      "levelColor": "#22c55e",
      "code": "N-3-2",
      "desc": "三位數退位減法情境題，購物情境，每題附商品圖片，個位均為 0，十位單退位。"
    },
    "sample": {
      "pdf": "assets/tuiwei3sub-yw_sample.pdf",
      "name": "退位減法（三位數）＿應用題＿購物篇_範本.pdf"
    },
    "layout": {
      "panel": "tuiwei3subYwPanel",
      "themeSet": "cheap",
      "showTheme": false,
      "prices": false,
      "interactive": false
    }
  },
  {
    "id": "huachu4add-en",
    "code": "N-3-1",
    "grade": "3",
    "name": "No-Carry Addition (4-digit) — Draw Coins",
    "ops": [
      "add"
    ],
    "keywords": [
      "draw coins",
      "4-digit",
      "no carry",
      "addition",
      "English"
    ],
    "desc": "5 four-digit no-carry addition problems with coin drawing aid. Writing practice: thousands digit 2→9, same last 3 digits, 8 blanks. Numbers randomized each time.",
    "sortKey": [
      1,
      4,
      1
    ],
    "home": {
      "icon": "🪙",
      "sub": "4-digit No-Carry Addition",
      "desc": "Draw coins to represent 4-digit numbers, solve 5 no-carry addition problems. Writing practice counts up by thousands.",
      "features": [
        "4-digit no-carry addition",
        "Coin drawing aid",
        "Thousands counting-up practice"
      ]
    },
    "diffInfo": {
      "grade": "Grade 3",
      "level": "Foundation",
      "levelColor": "#22c55e",
      "code": "N-3-1",
      "desc": "4-digit addition (no carrying). Students draw coins to understand place value. Suitable for introductory 4-digit addition practice."
    },
    "sample": {
      "pdf": "assets/huachu4add_en_sample.pdf",
      "name": "No-Carry-Addition_4-digit_Draw-Coins_sample.pdf"
    },
    "layout": {
      "panel": "huachu4addEnPanel",
      "themeSet": "cheap",
      "showTheme": false,
      "prices": false,
      "interactive": false
    }
  },
  {
    "id": "fenfennew",
    "code": "N-2-3",
    "grade": "2",
    "name": "分分看＿一步驟除法（兩位數）",
    "ops": [
      "div"
    ],
    "keywords": [
      "分分看",
      "幾組",
      "等分",
      "除法",
      "圖示"
    ],
    "desc": "選擇物件主題（花、動物、水果等），系統自動產生 6 道等分除法題組，每題展示圖示讓學生數數後填答。除數 2–6 隨機，A4 橫向雙欄版面。",
    "sortKey": [
      4,
      2,
      1
    ],
    "home": null,
    "diffInfo": {
      "grade": "二年級",
      "level": "基礎",
      "levelColor": "#22c55e",
      "code": "N-2-3",
      "desc": "以具體圖示輔助「等分除法」概念，數幾個、每幾個一組、共幾組，適合除法初學者。"
    },
    "sample": {
      "pdf": "assets/fenfennew_sample.pdf",
      "name": "分分看_一步驟除法_兩位數_範本.pdf"
    },
    "layout": {
      "panel": "fenfennewPanel",
      "themeSet": "cheap",
      "showTheme": false,
      "prices": false,
      "interactive": false
    }
  },
  {
    "id": "fenfen-rem",
    "code": "N-2-3",
    "grade": "2",
    "name": "分分看＿有餘數（兩位數）",
    "ops": [
      "div"
    ],
    "keywords": [
      "分分看",
      "有餘數",
      "圈圈看",
      "等組",
      "裝盤"
    ],
    "desc": "固定圖片版型，只換除數，確保每題有餘數（圖片數不被除數整除）。6 題，物品種類固定在模板中。",
    "sortKey": [
      4,
      2,
      1
    ],
    "home": null,
    "diffInfo": {
      "grade": "二年級",
      "level": "進階",
      "levelColor": "#f59e0b",
      "code": "N-2-3",
      "desc": "在等組除法基礎上加入餘數概念，圖示固定，學生圈圈後同時填入商與餘數。"
    },
    "sample": {
      "pdf": "assets/fenfen_rem_sample.pdf",
      "name": "分分看_有餘數_兩位數_範本.pdf"
    },
    "layout": {
      "panel": "fenfenPanel",
      "themeSet": null,
      "showTheme": false,
      "prices": false,
      "interactive": false
    }
  },
  {
    "id": "fenfen-heap",
    "code": "N-2-3",
    "grade": "2",
    "name": "分分看＿分堆畫圈（兩位數）",
    "ops": [
      "div"
    ],
    "keywords": [
      "分分看",
      "分堆",
      "畫圓圈",
      "等分",
      "平分"
    ],
    "desc": "把 N 個物品平分給 X 個人，學生畫圓圈表示分堆，4 題，數字每次隨機。",
    "sortKey": [
      4,
      2,
      1
    ],
    "home": null,
    "diffInfo": {
      "grade": "二年級",
      "level": "基礎",
      "levelColor": "#22c55e",
      "code": "N-2-3",
      "desc": "學生自己畫圓圈將物品平均分堆，建立等分除法的具體操作概念。"
    },
    "sample": {
      "pdf": "assets/fenfen_heap_sample.pdf",
      "name": "分分看_分堆畫圈_兩位數_範本.pdf"
    },
    "layout": {
      "panel": "fenfenPanel",
      "themeSet": null,
      "showTheme": false,
      "prices": false,
      "interactive": false
    }
  },
  {
    "id": "fenfen-pan",
    "code": "N-2-3",
    "grade": "2",
    "name": "分分看＿分盤畫圈（兩位數）",
    "ops": [
      "div"
    ],
    "keywords": [
      "分分看",
      "分盤",
      "畫圓圈",
      "等分",
      "平分",
      "無格線"
    ],
    "desc": "把 N 個物品平分給 X 個人，學生在盤形空間中畫圓圈，無格線，8 題（含 1 題範例），數字每次隨機。",
    "sortKey": [
      4,
      2,
      1
    ],
    "home": null,
    "diffInfo": {
      "grade": "二年級",
      "level": "基礎",
      "levelColor": "#22c55e",
      "code": "N-2-3",
      "desc": "在盤形空間中畫圓圈表示等分，無格線版提供較大自由度，適合初學等分概念。"
    },
    "sample": {
      "pdf": "assets/fenfen_pan_sample.pdf",
      "name": "分分看_分盤畫圈_兩位數_範本.pdf"
    },
    "layout": {
      "panel": "fenfenPanel",
      "themeSet": null,
      "showTheme": false,
      "prices": false,
      "interactive": false
    }
  },
  {
    "id": "fenfen-pangrid",
    "code": "N-2-3",
    "grade": "2",
    "name": "分分看＿分盤格線（兩位數）",
    "ops": [
      "div"
    ],
    "keywords": [
      "分分看",
      "分盤",
      "格線",
      "畫圓圈",
      "等分",
      "平分"
    ],
    "desc": "把 N 個物品平分給 X 個人，盤形空間有格線輔助，4 題，數字每次隨機。",
    "sortKey": [
      4,
      2,
      1
    ],
    "home": null,
    "diffInfo": {
      "grade": "二年級",
      "level": "基礎",
      "levelColor": "#22c55e",
      "code": "N-2-3",
      "desc": "格線輔助學生在盤中整齊排列圓圈，更有利於等分概念的視覺呈現。"
    },
    "sample": {
      "pdf": "assets/fenfen_pangrid_sample.pdf",
      "name": "分分看_分盤格線_兩位數_範本.pdf"
    },
    "layout": {
      "panel": "fenfenPanel",
      "themeSet": null,
      "showTheme": false,
      "prices": false,
      "interactive": false
    }
  },
  {
    "id": "sub2noreg",
    "code": "N-2-2",
    "name": "兩位數不退位減法＿直式計算",
    "grade": 2,
    "ops": [
      "sub"
    ],
    "keywords": [
      "兩位數",
      "不退位",
      "減法",
      "直式"
    ],
    "desc": "兩位數不退位減法直式計算，3 題示範（固定）+ 9 題練習（隨機），每次數字隨機。",
    "sortKey": [
      2,
      2,
      1
    ],
    "home": {
      "icon": "➖",
      "label": "兩位數不退位減法",
      "sub": "直式計算練習"
    },
    "diffInfo": {
      "grade": "二年級",
      "level": "基礎",
      "levelColor": "#22c55e",
      "code": "N-2-2",
      "desc": "兩位數不退位減法，3 題示範（題目與錢幣圖固定）＋ 9 題隨機練習，每次數字不同。"
    },
    "sample": "assets/sub2noreg_sample.pdf",
    "layout": {
      "panel": "sub2noregPanel",
      "themeSet": null,
      "showTheme": false,
      "prices": false,
      "interactive": false
    }
  },
  {
    "id": "sub2noreg-app",
    "code": "N-2-2",
    "name": "兩位數不退位減法＿應用題",
    "grade": 2,
    "ops": [
      "sub"
    ],
    "keywords": [
      "兩位數",
      "不退位",
      "減法",
      "應用題",
      "撲滿",
      "找錢"
    ],
    "desc": "兩位數不退位減法應用題，含撲滿版（12 題共用 X）、找幾個 10 元版、找 10 元+1 元版，每次數字隨機。",
    "sortKey": [
      2,
      2,
      2
    ],
    "home": {
      "icon": "🐷",
      "label": "兩位數不退位應用題",
      "sub": "撲滿 / 找零版"
    },
    "diffInfo": null,
    "sample": [
      {
        "pdf": "assets/sub2noreg-app_pman_sample.pdf",
        "name": "兩位數不退位減法應用題（撲滿版）.pdf",
        "label": "撲滿版",
        "key": "sub2noreg-app-pman"
      },
      {
        "pdf": "assets/sub2noreg-app_a_sample.pdf",
        "name": "兩位數不退位減法應用題（找幾個10元）.pdf",
        "label": "找幾個10元",
        "key": "sub2noreg-app-a"
      },
      {
        "pdf": "assets/sub2noreg-app_b_sample.pdf",
        "name": "兩位數不退位減法應用題（找零版）.pdf",
        "label": "找零版",
        "key": "sub2noreg-app-b"
      }
    ],
    "layout": {
      "panel": "sub2noregAppPanel",
      "themeSet": "cheap",
      "showTheme": true,
      "prices": false,
      "interactive": false
    },
    "variants": [
      { "key": "sub2noreg-app-pman", "label": "撲滿版" },
      { "key": "sub2noreg-app-a",    "label": "找幾個10元" },
      { "key": "sub2noreg-app-b",    "label": "找零版" }
    ]
  },
  {
    "id": "sub2borrow",
    "code": "N-2-2",
    "name": "兩位數退位減法＿直式計算",
    "grade": 2,
    "ops": [
      "sub"
    ],
    "keywords": [
      "兩位數",
      "退位",
      "減法",
      "直式",
      "個位退位"
    ],
    "desc": "兩位數退位減法直式計算，含示範版（8 題圖示退位過程）與練習版（3 題示範 + 21 題練習），每次數字隨機。",
    "sortKey": [
      2,
      2,
      3
    ],
    "home": {
      "icon": "🔢",
      "label": "兩位數退位減法",
      "sub": "直式計算練習"
    },
    "diffInfo": null,
    "sample": [
      { "pdf": "assets/sub2borrow_demo_sample.pdf", "name": "兩位數退位減法_標準版_範例.pdf", "label": "標準版", "key": "sub2borrow" },
      { "pdf": "assets/sub2borrow-1d_sample.pdf", "name": "兩位數退位減法_減個位數_範例.pdf", "label": "減個位數", "key": "sub2borrow-1d" }
    ],
    "layout": {
      "panel": "sub2borrowPanel",
      "themeSet": null,
      "showTheme": false,
      "prices": false,
      "interactive": false
    },
    "variants": [
      {
        "key": "sub2borrow",
        "label": "標準版"
      },
      {
        "key": "sub2borrow-1d",
        "label": "減個位數"
      }
    ]
  },
  {
    "id": "sub2borrow-1d",
    "code": "N-2-2",
    "name": "兩位數減個位數＿退位減法",
    "grade": 2,
    "ops": [
      "sub"
    ],
    "keywords": [
      "兩位數",
      "個位數",
      "退位",
      "減法"
    ],
    "desc": "兩位數減個位數的退位減法練習（被減數 11–19），2 題示範附個位拆分步驟，4 題練習，每次數字隨機。",
    "sortKey": [
      2,
      2,
      4
    ],
    "home": {
      "icon": "➖",
      "label": "兩位數減個位數",
      "sub": "退位減法"
    },
    "diffInfo": {
      "grade": "二年級",
      "level": "基礎",
      "levelColor": "#22c55e",
      "code": "N-2-2",
      "desc": "被減數 11–19，個位退位。2 題示範附拆分步驟，4 題隨機練習。"
    },
    "sample": "assets/sub2borrow-1d_sample.pdf",
    "layout": {
      "panel": "sub2borrow1dPanel",
      "themeSet": null,
      "showTheme": false,
      "prices": false,
      "interactive": false
    }
  },
  {
    "id": "sub3noreg-app",
    "code": "N-3-2",
    "name": "三位數不退位減法＿應用題",
    "grade": 3,
    "ops": [
      "sub"
    ],
    "keywords": [
      "三位數",
      "不退位",
      "減法",
      "應用題",
      "撲滿"
    ],
    "desc": "三位數不退位減法應用題，含三種版型：標準版（X 整十，Y 三位數）、被減數兩位版、混合版，每次數字隨機。",
    "sortKey": [
      2,
      3,
      3
    ],
    "home": {
      "icon": "🐷",
      "label": "三位數不退位應用題",
      "sub": "撲滿情境"
    },
    "diffInfo": null,
    "sample": [
      {
        "pdf": "assets/sub3noreg-app_std_sample.pdf",
        "name": "三位數不退位減法應用題（標準版）.pdf",
        "label": "標準版",
        "key": "sub3noreg-app-std"
      },
      {
        "pdf": "assets/sub3noreg-app_2digit_sample.pdf",
        "name": "三位數不退位減法應用題（被減數兩位版）.pdf",
        "label": "被減數兩位版",
        "key": "sub3noreg-app-2digit"
      },
      {
        "pdf": "assets/sub3noreg-app_mixed_sample.pdf",
        "name": "三位數不退位減法應用題（混合版）.pdf",
        "label": "混合版",
        "key": "sub3noreg-app-mixed"
      }
    ],
    "layout": {
      "panel": "sub3noregAppPanel",
      "themeSet": "cheap",
      "showTheme": true,
      "prices": false,
      "interactive": false
    },
    "variants": [
      { "key": "sub3noreg-app-std",    "label": "標準版" },
      { "key": "sub3noreg-app-2digit", "label": "被減數兩位版" },
      { "key": "sub3noreg-app-mixed",  "label": "混合版" }
    ]
  },
  {
    "id": "sub3borrow",
    "code": "N-3-2",
    "name": "三位數退位減法＿直式計算",
    "grade": 3,
    "ops": [
      "sub"
    ],
    "keywords": [
      "三位數",
      "退位",
      "減法",
      "直式"
    ],
    "desc": "三位數退位減法直式計算，6 題練習，三種格式混合（整體式、個位拆分式、百十位拆分式），每次數字隨機。",
    "sortKey": [
      2,
      3,
      4
    ],
    "home": {
      "icon": "🔢",
      "label": "三位數退位減法",
      "sub": "直式計算練習"
    },
    "diffInfo": {
      "grade": "三年級",
      "level": "基礎",
      "levelColor": "#22c55e",
      "code": "N-3-2",
      "desc": "三位數退位減法，6 題練習，三種呈現方式（整體式、個位拆分、百十位拆分），每次數字隨機。"
    },
    "sample": "assets/sub3borrow_sample.pdf",
    "layout": {
      "panel": "sub3borrowPanel",
      "themeSet": null,
      "showTheme": false,
      "prices": false,
      "interactive": false
    }
  },
  {
    "id": "coinvalue",
    "code": "coinvalue",
    "name": "認識錢幣＿至百位",
    "grade": 2,
    "ops": [
      "add"
    ],
    "keywords": [
      "coinvalue",
      "money",
      "錢幣",
      "位值板"
    ],
    "desc": "數一數位值板上的錢幣，一共多少元？循序漸進認識 100/10/1、5、50、500 元。",
    "sortKey": [
      1,
      2,
      1
    ],
    "home": {
      "badge": "認識錢幣",
      "title": "認識錢幣＿至百位",
      "sub": "5 個難度層次 × 2 種風格",
      "tags": [
        "加法",
        "二年級",
        "錢幣"
      ]
    },
    "diffInfo": null,
    "sample": [
      {
        "pdf": "assets/coinvalue_L1_simple_sample.pdf",
        "name": "認識錢幣_至百位_L1_範本.pdf",
        "label": "L1"
      },
      {
        "pdf": "assets/coinvalue_L2_simple_sample.pdf",
        "name": "認識錢幣_至百位_L2_範本.pdf",
        "label": "L2"
      },
      {
        "pdf": "assets/coinvalue_L3_simple_sample.pdf",
        "name": "認識錢幣_至百位_L3_範本.pdf",
        "label": "L3"
      },
      {
        "pdf": "assets/coinvalue_L4_simple_sample.pdf",
        "name": "認識錢幣_至百位_L4_範本.pdf",
        "label": "L4"
      },
      {
        "pdf": "assets/coinvalue_L5_simple_sample.pdf",
        "name": "認識錢幣_至百位_L5_範本.pdf",
        "label": "L5"
      }
    ],
    "layout": {
      "panel": "coinvaluePanel",
      "themeSet": null,
      "showTheme": false,
      "prices": false,
      "interactive": false
    }
  },
  {
    "id": "coinvalue1000",
    "code": "coinvalue1000",
    "name": "認識錢幣＿至千位",
    "grade": 3,
    "ops": [
      "add"
    ],
    "keywords": [
      "coinvalue",
      "money",
      "錢幣",
      "位值板",
      "千位"
    ],
    "desc": "數一數位值板上的錢幣，一共多少元？（含千位欄）循序漸進認識 1000/100/10/1、5、50、500 元。",
    "sortKey": [
      1,
      3,
      1
    ],
    "home": {
      "badge": "認識錢幣",
      "title": "認識錢幣＿至千位",
      "sub": "5 個難度層次，含千元",
      "tags": [
        "加法",
        "三年級",
        "錢幣"
      ]
    },
    "diffInfo": null,
    "sample": [
      {
        "pdf": "assets/coinvalue1000_L1_simple_sample.pdf",
        "name": "認識錢幣_至千位_L1_範本.pdf",
        "label": "L1"
      },
      {
        "pdf": "assets/coinvalue1000_L2_simple_sample.pdf",
        "name": "認識錢幣_至千位_L2_範本.pdf",
        "label": "L2"
      },
      {
        "pdf": "assets/coinvalue1000_L3_simple_sample.pdf",
        "name": "認識錢幣_至千位_L3_範本.pdf",
        "label": "L3"
      },
      {
        "pdf": "assets/coinvalue1000_L4_simple_sample.pdf",
        "name": "認識錢幣_至千位_L4_範本.pdf",
        "label": "L4"
      },
      {
        "pdf": "assets/coinvalue1000_L5_simple_sample.pdf",
        "name": "認識錢幣_至千位_L5_範本.pdf",
        "label": "L5"
      }
    ],
    "layout": {
      "panel": "coinvalue1000Panel",
      "themeSet": null,
      "showTheme": false,
      "prices": false,
      "interactive": false
    }
  },
  {
    "id": "coincarry",
    "code": "coincarry",
    "name": "認識錢幣＿進位（至百位）",
    "grade": 2,
    "ops": [
      "coin"
    ],
    "keywords": [
      "coincarry",
      "money",
      "錢幣",
      "進位",
      "至百位"
    ],
    "desc": "位值板上十位欄有 10–14 枚錢幣，練習進位換算至百位。L2 十位10元進百位、L4 加入50元。",
    "sortKey": [
      1,
      2,
      1
    ],
    "home": {
      "badge": "錢幣進位",
      "title": "認識錢幣＿進位（至百位）",
      "sub": "2 個難度，十位進百位",
      "tags": [
        "加法",
        "二年級",
        "錢幣",
        "進位"
      ]
    },
    "diffInfo": null,
    "sample": [
      {
        "pdf": "assets/coincarry_L2_simple_sample.pdf",
        "name": "認識錢幣_進位至百位_L2_範本.pdf",
        "label": "L2"
      },
      {
        "pdf": "assets/coincarry_L3_simple_sample.pdf",
        "name": "認識錢幣_進位至百位_L3_範本.pdf",
        "label": "L3"
      },
      {
        "pdf": "assets/coincarry_L4_simple_sample.pdf",
        "name": "認識錢幣_進位至百位_L4_範本.pdf",
        "label": "L4"
      }
    ],
    "layout": {
      "panel": "coincarryPanel",
      "themeSet": null,
      "showTheme": false,
      "prices": false,
      "interactive": false
    }
  },
  {
    "id": "coincarry10",
    "code": "coincarry10",
    "name": "認識錢幣＿進位（至十位）",
    "grade": 2,
    "ops": [
      "coin"
    ],
    "keywords": [
      "coincarry",
      "money",
      "錢幣",
      "進位",
      "至十位"
    ],
    "desc": "位值板上個位欄有 10–14 枚錢幣，練習進位換算至十位。L1 個位1元進十位、L3 加入5元。",
    "sortKey": [
      1,
      1,
      1
    ],
    "home": {
      "badge": "錢幣進位",
      "title": "認識錢幣＿進位（至十位）",
      "sub": "2 個難度，個位進十位",
      "tags": [
        "加法",
        "二年級",
        "錢幣",
        "進位"
      ]
    },
    "diffInfo": null,
    "sample": {
      "pdf": "assets/coincarry_L1_simple_sample.pdf",
      "name": "認識錢幣_進位至十位_範本.pdf"
    },
    "layout": {
      "panel": "coincarry10Panel",
      "themeSet": null,
      "showTheme": false,
      "prices": false,
      "interactive": false
    }
  },
  {
    "id": "coincarry1000",
    "code": "coincarry1000",
    "name": "認識錢幣＿進位（至千位）",
    "grade": 3,
    "ops": [
      "coin"
    ],
    "keywords": [
      "coincarry",
      "coincarry1000",
      "money",
      "錢幣",
      "進位",
      "至千位"
    ],
    "desc": "位值板上百位欄有 10–14 枚錢幣，練習進位到千位。L1 純100元進位、L2 加入500元。",
    "sortKey": [
      1,
      3,
      1
    ],
    "home": {
      "badge": "錢幣進位",
      "title": "認識錢幣＿進位（至千位）",
      "sub": "2 個難度，百位進千位",
      "tags": [
        "加法",
        "三年級",
        "錢幣",
        "進位"
      ]
    },
    "diffInfo": null,
    "sample": [
      {
        "pdf": "assets/coincarry1000_L1_simple_sample.pdf",
        "name": "認識錢幣_進位至千位_L1_範本.pdf",
        "label": "L1"
      },
      {
        "pdf": "assets/coincarry1000_L2_simple_sample.pdf",
        "name": "認識錢幣_進位至千位_L2_範本.pdf",
        "label": "L2"
      }
    ],
    "layout": {
      "panel": "coincarry1000Panel",
      "themeSet": null,
      "showTheme": false,
      "prices": false,
      "interactive": false
    }
  },
  {
    "id": "l6_01",
    "code": "N-1-1",
    "name": "數到200＿餅乾計數",
    "grade": 1,
    "ops": [],
    "keywords": [
      "數到200",
      "計數",
      "一百多",
      "餅乾"
    ],
    "desc": "認識 151–200：用餅乾圖像計數，每格一包（10 個）或一個，固定版型。",
    "sortKey": [
      1,
      2,
      1
    ],
    "home": {
      "icon": "🍪",
      "sub": "認識 151–200",
      "desc": "用餅乾圖像認識 151–200，固定版型，一鍵下載。",
      "features": [
        "固定版型",
        "圖像計數",
        "一年級"
      ]
    },
    "diffInfo": {
      "grade": "一年級",
      "level": "基礎",
      "levelColor": "#22c55e",
      "code": "N-1-1",
      "desc": "用具象圖像（餅乾）計數，認識 151–200 的位值結構。"
    },
    "sample": "assets/l6_01_sample.pdf",
    "layout": {
      "panel": "l6_01Panel",
      "themeSet": null,
      "showTheme": false,
      "prices": false,
      "interactive": false
    }
  },
  {
    "id": "l6_02",
    "code": "N-1-1",
    "name": "數到200＿香蕉計數",
    "grade": 1,
    "ops": [],
    "keywords": [
      "數到200",
      "計數",
      "一百多",
      "香蕉"
    ],
    "desc": "認識 151–200：用香蕉圖像計數，每串十根或一根，固定版型。",
    "sortKey": [
      1,
      2,
      1
    ],
    "home": {
      "icon": "🍌",
      "sub": "認識 151–200",
      "desc": "用香蕉圖像認識 151–200，固定版型，一鍵下載。",
      "features": [
        "固定版型",
        "圖像計數",
        "一年級"
      ]
    },
    "diffInfo": {
      "grade": "一年級",
      "level": "基礎",
      "levelColor": "#22c55e",
      "code": "N-1-1",
      "desc": "用具象圖像（香蕉）計數，認識 151–200 的位值結構。"
    },
    "sample": "assets/l6_02_sample.pdf",
    "layout": {
      "panel": "l6_02Panel",
      "themeSet": null,
      "showTheme": false,
      "prices": false,
      "interactive": false
    }
  },
  {
    "id": "l6_03",
    "code": "N-1-1",
    "name": "數到200＿混合計數",
    "grade": 1,
    "ops": [],
    "keywords": [
      "數到200",
      "計數",
      "一百多",
      "混合"
    ],
    "desc": "認識 151–200：餅乾＋香蕉混合計數，固定版型。",
    "sortKey": [
      1,
      2,
      1
    ],
    "home": {
      "icon": "🔢",
      "sub": "混合計數 151–200",
      "desc": "餅乾＋香蕉混合計數，認識 151–200，固定版型。",
      "features": [
        "固定版型",
        "混合圖像",
        "一年級"
      ]
    },
    "diffInfo": {
      "grade": "一年級",
      "level": "基礎",
      "levelColor": "#22c55e",
      "code": "N-1-1",
      "desc": "用餅乾和香蕉兩種圖像混合計數，認識 151–200。"
    },
    "sample": "assets/l6_03_sample.pdf",
    "layout": {
      "panel": "l6_03Panel",
      "themeSet": null,
      "showTheme": false,
      "prices": false,
      "interactive": false
    }
  },
  {
    "id": "l6_04",
    "code": "N-1-1",
    "name": "數到200＿積木十位個位",
    "grade": 1,
    "ops": [],
    "keywords": [
      "數到200",
      "積木",
      "十位",
      "個位",
      "位值"
    ],
    "desc": "認識 151–200：用積木圖示表示十位與個位，理解位值結構，固定版型。",
    "sortKey": [
      1,
      2,
      2
    ],
    "home": {
      "icon": "🧱",
      "sub": "積木十位個位",
      "desc": "積木圖示表示十位＋個位，理解 151–200 位值結構。",
      "features": [
        "固定版型",
        "積木位值",
        "一年級"
      ]
    },
    "diffInfo": {
      "grade": "一年級",
      "level": "基礎",
      "levelColor": "#22c55e",
      "code": "N-1-1",
      "desc": "用積木圖示（長條十位＋方塊個位）表示 151–200。"
    },
    "sample": "assets/l6_04_sample.pdf",
    "layout": {
      "panel": "l6_04Panel",
      "themeSet": null,
      "showTheme": false,
      "prices": false,
      "interactive": false
    }
  },
  {
    "id": "l6_05",
    "code": "N-1-1",
    "name": "數到200＿積木百位",
    "grade": 1,
    "ops": [],
    "keywords": [
      "數到200",
      "積木",
      "百位",
      "位值"
    ],
    "desc": "認識 151–200：用積木圖示表示百位，理解三位數位值結構，固定版型。",
    "sortKey": [
      1,
      2,
      3
    ],
    "home": {
      "icon": "🧊",
      "sub": "積木百位",
      "desc": "積木圖示表示百位，理解三位數位值，固定版型。",
      "features": [
        "固定版型",
        "積木百位",
        "一年級"
      ]
    },
    "diffInfo": {
      "grade": "一年級",
      "level": "基礎",
      "levelColor": "#22c55e",
      "code": "N-1-1",
      "desc": "用大積木方塊表示百位，認識 151–200 三位數結構。"
    },
    "sample": "assets/l6_05_sample.pdf",
    "layout": {
      "panel": "l6_05Panel",
      "themeSet": null,
      "showTheme": false,
      "prices": false,
      "interactive": false
    }
  },
  {
    "id": "l6_06",
    "code": "N-1-1",
    "name": "數到200＿錢幣計數",
    "grade": 1,
    "ops": [],
    "keywords": [
      "數到200",
      "錢幣",
      "計數",
      "一百多"
    ],
    "desc": "認識 151–200：用 100 元、10 元、1 元錢幣計數，固定版型。",
    "sortKey": [
      1,
      2,
      4
    ],
    "home": {
      "icon": "💰",
      "sub": "錢幣計數 151–200",
      "desc": "用 100/10/1 元錢幣計數，認識 151–200，固定版型。",
      "features": [
        "固定版型",
        "錢幣計數",
        "一年級"
      ]
    },
    "diffInfo": {
      "grade": "一年級",
      "level": "基礎",
      "levelColor": "#22c55e",
      "code": "N-1-1",
      "desc": "用 100 元、10 元、1 元錢幣組合，計數到 200。"
    },
    "sample": "assets/l6_06_sample.pdf",
    "layout": {
      "panel": "l6_06Panel",
      "themeSet": null,
      "showTheme": false,
      "prices": false,
      "interactive": false
    }
  },
  {
    "id": "l6_07",
    "code": "N-1-1",
    "name": "數到200＿數字填空",
    "grade": 1,
    "ops": [],
    "keywords": [
      "數到200",
      "數字",
      "填空",
      "一百多",
      "數列"
    ],
    "desc": "151–200 與 351–400 兩段數字格，隨機 32/50 格顯示，其餘格學生填寫。",
    "sortKey": [
      1,
      2,
      5
    ],
    "home": {
      "icon": "📝",
      "sub": "數字填空（隨機）",
      "desc": "151–200 與 351–400 數列填空，每次隨機 32/50 格顯示。",
      "features": [
        "每次隨機",
        "數字填空",
        "一年級"
      ]
    },
    "diffInfo": {
      "grade": "一年級",
      "level": "基礎",
      "levelColor": "#22c55e",
      "code": "N-1-1",
      "desc": "151–200 與 351–400 兩段數列，每次隨機選 32 格顯示，其餘格讓學生填寫。"
    },
    "sample": "assets/l6_07_sample.pdf",
    "layout": {
      "panel": "l6_07Panel",
      "themeSet": null,
      "showTheme": false,
      "prices": false,
      "interactive": false
    }
  },
  {
    "id": "l6_08",
    "code": "N-1-1",
    "name": "數到200＿錢幣比大小",
    "grade": 1,
    "ops": [],
    "keywords": [
      "數到200",
      "比大小",
      "錢幣",
      "三位數"
    ],
    "desc": "用畫錢幣的方式比較兩個三位數大小，示範題固定，練習題每次隨機（101–199）。",
    "sortKey": [
      1,
      2,
      6
    ],
    "home": {
      "icon": "⚖️",
      "sub": "錢幣比大小",
      "desc": "畫錢幣比較兩個三位數大小，練習數字每次隨機。",
      "features": [
        "每次隨機",
        "比大小",
        "一年級"
      ]
    },
    "diffInfo": {
      "grade": "一年級",
      "level": "基礎",
      "levelColor": "#22c55e",
      "code": "N-1-1",
      "desc": "示範題比較 143 與 156，練習題比較隨機產生的兩個 101–199 三位數。"
    },
    "sample": "assets/l6_08_sample.pdf",
    "layout": {
      "panel": "l6_08Panel",
      "themeSet": null,
      "showTheme": false,
      "prices": false,
      "interactive": false
    }
  },
  {
    "id": "compare-qty",
    "code": "N-1-2",
    "name": "比誰多誰少",
    "grade": 1,
    "ops": [],
    "keywords": ["compare-qty", "比誰多誰少", "數量比較"],
    "desc": "比較兩堆數量（1–10）的多少，打勾作答，共四種版型：統一圖案、相同圖案互比、不同圖案互比、簡單文字圖。",
    "sortKey": [1, 1, 1],
    "home": {
      "icon": "🆚",
      "sub": "數量比較",
      "desc": "比較兩堆數量（1–10）的多少，打勾作答。",
      "features": ["每次隨機", "數量比較", "一年級"]
    },
    "diffInfo": null,
    "sample": [
      { "pdf": "assets/compare-qty_unified_sample.pdf", "name": "比誰多誰少_統一圖案_範例.pdf", "label": "統一圖案", "key": "compare-qty-unified" },
      { "pdf": "assets/compare-qty_same_sample.pdf",    "name": "比誰多誰少_相同圖案互比_範例.pdf", "label": "相同圖案互比", "key": "compare-qty-same" },
      { "pdf": "assets/compare-qty_diff_sample.pdf",    "name": "比誰多誰少_不同圖案互比_範例.pdf", "label": "不同圖案互比", "key": "compare-qty-diff" },
      { "pdf": "assets/compare-qty_text_sample.pdf",    "name": "比誰多誰少_簡單文字圖_範例.pdf", "label": "簡單文字圖", "key": "compare-qty-text" }
    ],
    "layout": {
      "panel": "compareQtyPanel",
      "themeSet": null,
      "showTheme": false,
      "prices": false,
      "interactive": false
    },
    "variants": [
      { "key": "compare-qty-unified", "label": "統一圖案" },
      { "key": "compare-qty-same",    "label": "相同圖案互比" },
      { "key": "compare-qty-diff",    "label": "不同圖案互比" },
      { "key": "compare-qty-text",    "label": "簡單文字圖" }
    ]
  }
];
